version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db # Montar la carpeta donde se guarda la base de datos
    depends_on:
      - backend
    environment:
      - DATABASE_URL=sqlite:///app/db/db.sqlite3 # Ruta de la base de datos SQLite

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  backend-db:
