version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    environment:
      - DATABASE_URL=sqlite:///app/db/db.sqlite3

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Este volumen anónimo preserva node_modules
    depends_on:
      - backend


volumes:
  backend-db: